#!/usr/bin/perl

use strict;
use warnings;
use FindBin qw($Bin);
use File::Basename qw(dirname);
use File::Path qw(mkpath rmtree);

my $compiler = $ENV{RETROWEBKIT_GXX} || '/opt/local/bin/g++-mp-6';
my @arguments;
my @sdk_include_roots;
my $is_objective_cxx = 0;

sub add_header_map_overlay
{
    my ($path) = @_;
    open my $file, '<', $path or return;
    binmode $file;
    local $/;
    my $data = <$file>;
    close $file;
    return unless defined $data && length($data) >= 24;

    my ($magic, $version, $reserved, $strings_offset, $entries, $buckets) =
        unpack('NnnNNN', substr($data, 0, 20));
    return unless $magic == 0x686d6170 && $version == 1 && $reserved == 0;
    return unless 24 + $buckets * 12 <= length($data) && $strings_offset < length($data);

    my @metadata = stat($path);
    return unless @metadata;
    my $overlay = "$path.gcc6-v3-$metadata[1]-$metadata[7]-$metadata[9]";
    if (-d $overlay) {
        push @arguments, "-I$overlay";
        return;
    }

    my $temporary_overlay = "$overlay.$$";
    rmtree($temporary_overlay) if -e $temporary_overlay;
    mkpath($temporary_overlay);

    my $string_at = sub {
        my ($offset) = @_;
        return '' unless $offset;
        my $start = $strings_offset + $offset;
        return '' if $start >= length($data);
        my $end = index($data, "\0", $start);
        return '' if $end < 0;
        return substr($data, $start, $end - $start);
    };

    for my $index (0 .. $buckets - 1) {
        my ($key_offset, $prefix_offset, $suffix_offset) =
            unpack('N3', substr($data, 24 + $index * 12, 12));
        next unless $key_offset;
        my $key = $string_at->($key_offset);
        my $value = $string_at->($prefix_offset) . $string_at->($suffix_offset);
        next unless length($key) && length($value);
        next if $key =~ m!^/! || $key =~ m!(?:^|/)\.\.(?:/|$)!;
        my $destination = "$temporary_overlay/$key";
        mkpath(dirname($destination));
        # Preserve #import's once-only behavior when one physical header has
        # multiple header-map keys (for example Foo.h and WebKit/Foo.h).
        # Separate redirect files make GCC treat those aliases as distinct.
        next if symlink($value, $destination);

        my $escaped_value = $value;
        $escaped_value =~ s!([\\"])!\\$1!g;
        if (open my $redirect, '>', $destination) {
            print {$redirect} "#include \"$escaped_value\"\n";
            close $redirect;
        }
    }

    unless (rename($temporary_overlay, $overlay)) {
        rmtree($temporary_overlay);
        return unless -d $overlay;
    }
    push @arguments, "-I$overlay";
}

while (@ARGV) {
    my $argument = shift @ARGV;
    $is_objective_cxx = 1 if $argument eq 'objective-c++' && @arguments && $arguments[-1] eq '-x';
    next if $argument eq '-fpascal-strings'
        || $argument eq '-Wnewline-eof'
        || $argument eq '-Wshorten-64-to-32';
    if ($argument eq '-lsqlite3' && -f '/opt/local/lib/libsqlite3.dylib') {
        push @arguments, '/opt/local/lib/libsqlite3.dylib';
        next;
    }
    if ($argument eq '-isysroot' && @ARGV) {
        my $sdk_root = shift @ARGV;
        push @arguments, $argument, $sdk_root;
        my $libxml2_root = "$sdk_root/usr/include/libxml2";
        push @sdk_include_roots, $libxml2_root if -d $libxml2_root;
        next;
    }
    if (($argument eq '-I' || $argument eq '-iquote') && @ARGV && $ARGV[0] =~ /\.hmap$/) {
        add_header_map_overlay(shift @ARGV);
        next;
    }
    if ($argument =~ /^-I(.*\.hmap)$/ || $argument =~ /^-iquote(.*\.hmap)$/) {
        add_header_map_overlay($1);
        next;
    }
    push @arguments, $argument;
}
if (grep { $_ eq '-c' || $_ eq '-E' || $_ eq '-S' } @arguments) {
    push @arguments, map { "-I$_" } @sdk_include_roots;
    push @arguments, "-I$Bin/MacPortsHeaders" if -f '/opt/local/include/sqlite3.h';
    push @arguments, '-include', "$Bin/LeopardMathCompatibility.h";
    push @arguments, '-Wno-error=strict-aliasing', '-Wno-error=multichar';
}
push @arguments, '-fobjc-exceptions', '-Wno-error' if $is_objective_cxx;

exec {$compiler} $compiler, @arguments;
die "error: could not execute $compiler: $!\n";
